// Session represents a developer's active Claude Code session
export interface Session {
  session_id: string;
  developer_email: string;
  developer_name: string;
  repo: string;
  project_path: string;
  started_at: string;       // ISO 8601
  last_activity: string;    // ISO 8601
  status: SessionStatus;
  intent: string | null;
  files_touched: string[];
  areas: string[];          // directories being worked in
}

export type SessionStatus = 'active' | 'idle' | 'ended';

// Signal represents a single captured developer action
export interface Signal {
  signal_id: string;
  session_id: string;
  timestamp: string;
  type: SignalType;
  content: string;
  file_path: string | null;
  semantic_area: string | null;
  weight: number;  // 0.0 (fully decayed) to 1.0 (fresh). Initialized to 1.0.
}

export type SignalType =
  // Phase 2 (existing)
  | 'prompt' | 'file_modify' | 'file_read' | 'search' | 'explicit'
  // Phase 3 — richer taxonomy
  | 'intent_declared'        // what the agent's human wants to accomplish
  | 'outcome_achieved'       // work completed, merged, deployed
  | 'blocker_hit'            // something is stuck
  | 'context_needed'         // agent needs more information to proceed
  | 'dependency_discovered'  // this work depends on something else
  | 'state_report';          // periodic snapshot from an orchestration nerve

// Collision represents detected overlap between sessions
export interface Collision {
  collision_id: string;
  session_ids: string[];
  type: CollisionType;
  severity: CollisionSeverity;
  details: string;
  detected_at: string;
  resolved: boolean;
  resolved_by: string | null;
}

export type CollisionType = 'file' | 'directory' | 'semantic';
export type CollisionSeverity = 'critical' | 'warning' | 'info';

// Repo tracked by the backend
export interface TrackedRepo {
  repo_id: string;
  name: string;
  provider: GitProvider;
  remote_url: string | null;
  discovered_at: string;
  last_activity: string | null;
}

export type GitProvider = 'github' | 'azure-devops' | 'gitlab' | 'self-registered';

// Agent Mail — persistent inter-agent messages surviving session boundaries
export interface AgentMail {
  mail_id: string;
  from_session_id: string | null;  // null = generated by consciousness
  to_session_id: string | null;    // null = addressed to "anyone working on X"
  to_context_id: string | null;    // A2A-inspired: addressed to a workstream
  type: AgentMailType;
  subject: string;
  content: string;
  created_at: string;
  read_at: string | null;
  weight: number;                  // decays like signals
}

export type AgentMailType =
  | 'collision_alert'       // consciousness detected overlap
  | 'context_share'         // agent sharing relevant context
  | 'dependency_notice'     // "my work depends on / affects yours"
  | 'blocker_notice'        // "I'm stuck on something in your area"
  | 'completion_notice'     // "I finished work relevant to you"
  | 'general';              // freeform
